services:
    adminer:
        container_name: quick-dev-adminer
        image: ghcr.io/shyim/adminerevo:latest
        restart: always
        ports:
            - "8080:8080"
        networks:
            - quick-dev-network
    buggregator:
        container_name: quick-dev-debug
        image: ghcr.io/buggregator/server:latest
        restart: always
        ports:
            - "8000:8000"
            - "1025:1025"
            - "9912:9912"
            - "2112:2112"
        networks:
            - quick-dev-network
    caddy:
        container_name: quick-dev-caddy
        image: caddy:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./sites/:/srv/www
            - ./.docker/images/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./.docker/caddy:/etc/caddy/sites
        networks:
            - quick-dev-network

networks:
    quick-dev-network:
        external: true