services:
    adminer:
        container_name: quick-dev-adminer
        image: ghcr.io/shyim/adminerevo:latest
        ports:
            - "8080:8080"
        networks:
            - quick-dev-network
    buggregator:
        container_name: quick-dev-buggregator
        image: ghcr.io/buggregator/server:latest
        ports:
            - "8000:8000"
            - "1025:1025"
            - "9912:9912"
            - "2112:2112"
        networks:
            - quick-dev-network
    caddy:
        container_name: quick-dev-caddy
        image: caddy:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./apps/:/srv/www
            - ./.docker/images/caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./.docker/caddy:/etc/caddy/sites
        networks:
            - quick-dev-network
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: quick-dev-keycloak
        ports:
            - "8081:8080"
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        command: start-dev
        networks:
            - quick-dev-network
    selenium-hub:
        container_name: quick-dev-selenium-hub
        image: selenium/hub:latest
        networks:
        - quick-dev-network
        ports:
        - "4442:4442"
        - "4443:4443"
        - "4444:4444"
    chrome:
        container_name: quick-dev-chrome
        image: selenium/node-chrome:latest
        shm_size: 2g
        depends_on:
        - selenium-hub
        environment:
        - SE_EVENT_BUS_HOST=quick-dev-selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        ports:
        - "7901:7900"
        networks:
        - quick-dev-network
    firefox:
        container_name: quick-dev-firefox
        image: selenium/node-firefox:latest
        shm_size: 2g
        depends_on:
        - selenium-hub
        environment:
        - SE_EVENT_BUS_HOST=quick-dev-selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        ports:
        - "7902:7900"
        networks:
        - quick-dev-network
    answer:
        container_name: quick-dev-answer
        image: apache/answer
        ports:
        - '8082:80'
        restart: on-failure
        volumes:
        - answer-data:/data
volumes:
    answer-data:

networks:
    quick-dev-network:
        external: true